### ISSUE TITLE
Outreach of the R Development Guide

### ISSUE THREAD

**Issue by SaranjeetKaur** [r-devel/rcontribution#11]
Coming up and executing sustainable ideas that would help with the outreach of the R Developer's Guide.

**Comment by hturner** [comment]
@SaranjeetKaur and I have discussed this a bit further offline, coming up with the following ideas:

## Monthly Challenge

Direct people to read particular parts of the guide and put together a challenge for them to test out what they have learned, using real case studies where possible. Examples:

 - Learn how to write a good bug report
 - Learn how to review a bug report
 - Create a personalized checklist for testing pre-release R versions
 - Learn how to contribute a translated R message
 
This would be announced on R Weekly, advertised on Twitter and Slack (see #14).

We could have a Slack channel for discussion about the monthly challenge and get people to report any issues they faced with the guide or official documentation.

This is an iteration on the book club idea, with the advantage that people can join in according to interest/background and there is a goal to aim for to give a sense of achievement.

## Meetups

We could have online meetups with R-Ladies Remote and the MiR community to tie in with the monthly challenges. These would actively encourage people from under-represented groups to engage. They could be run at distinct times to cover different time zones. RUGs could be encouraged to run their own tie-in events, if interested.

## Monitoring

The R Foundation have already agreed to fund a https://plausible.io/ subscription so that we can monitor the effect of the above or any other outreach we do to engage people with the guide.

**Comment by hturner** [comment]
These are now named Collaboration Campfires and scheduled as here: https://twitter.com/R_Contributors/status/1484524996701855747

**Comment by hturner** [comment]
Things to do in preparation for Collaboration Campfires before first event on Feb 22

- [ ] Add HackMDs from community champions consultation to rcontribution repo (Saranjeet, w/b 31 Jan)
- [ ] Create page on R Contribution Site giving overview of series that is currently planned 
    * Prepare first draft (Saranjeet, w/b 31 Jan)
    * Get feedback from community champions (Heather/Saranjeet, w/b 31 Jan)
    * Update site (Heather, w/b 7 Feb)
- [ ] Invite a couple of experienced contributors to attend first and/or second event (Heather w/b 31 Jan)
- [ ] Promotion to individuals/companies known to us/recommended by community champions (Heather, w/b 7 Feb)
- [ ] Initial promotion on Twitter/Slack/mailing lists (Heather, w/b 7 Feb)
- [ ] Prep for first session in more detail (Heather, w/b 7 Feb)
    * E.g. supporting slides, test out activities
- [ ] Promotion via the R Consortium (Saranjeet, w/b 14 Feb)
    * Promote to companies, asking them to promote event to staff and encourage their participation as a way to support the R project
    * Promote to R Consortium Working Groups - people already interested in contributing
 - [ ] Record R podcast episode (Heather & Saranjeet, w/b 14 Feb)
 - [ ] Follow-up promotion on Twitter (Saranjeet, w/b 14 Feb)
 - [ ] Follow-up promotion on Twitter (Saranjeet, w/b 21 Feb)

**Comment by hturner** [comment]
February 14 is "I love free software day" (https://fsfe.org/activities/ilovefs/index.en.html) - we should co-ordinate a tweet or two with that.

**Comment by hturner** [comment]
Things to do in preparation for Collaboration Campfires on Mar 22
- [ ] Email registered participants for session 1 not on Slack to encourage them to join Slack (Saranjeet, by 27 Feb)
- [ ] Attendance certificates (Saranjeet, by 27 Feb)
- [ ] Add podcast link in getting-started channel  (Saranjeet, by 27 Feb)
- [ ] Add the code conduct link to the Collaboration Campfires website (Heather, sometime)
- [ ] Invite experienced bug reviewers if they can come to (part of) session (Heather, w/b 28 Feb)
- [ ] Contact Laura (RC marketing manager) to help promote next time (Saranjeet, w/b 7 Mar)
- [ ] Initial promotion on Twitter/Slack/mailing lists (Heather and Saranjeet, w/b 7 Mar)
- [ ] Optional pre-reading: chapter on bug review - suggest on Slack/Twitter (Heather and Saranjeet, w/b 7 Mar)
- [ ] Prep for first session in more detail, i.e. skeleton for collaborative notes, test out activities (Heather and Saranjeet, w/b 7 Mar)
    * Poll (while people join): Did you come to the first session?
    * Logistics (Zoom, code of conduct, etherpad, etc). More than one written room?
    * Discuss take-home activities from session 1 - if anyone posted a plot/table
        * Poll: did they sign up for Bugzilla?
    * Poll: did they do the pre-reading? (One option: I already know about bug review)
    * In introduction, give examples of good and bad bug reports (bit of discussion from participants with experience)
    * Use Activity 3 from last time as Activity 1 for next time:
        * Look at report that already has several comment (first part of the activity).
    * One more longer/structured activity - practice reviewing one or more bug, e.g. 
        1. Review the bug report against good practice. Does it have a reprex? Does it have session info? Does it OS/machine architecture? Is the issue clear?
        2. Confirm bug on their machine.
        3. Diagnose cause of bug if possible (or discuss!)
    * If we find anything to follow up on (e.g. a possible comment to add to bug report), post on #getting-started channel to discuss how to move forward. 
    * Allow more time for feedback/discussion in the session 
    * Take home activity: repeat activity 2 on a different bug.
    * In future, when reviewing bugs use #work-out-loud channel.
 - [ ] Follow-up promotion on Twitter (Saranjeet, w/b 14 Mar)
 - [ ] Follow-up promotion on Twitter (Saranjeet, w/b 21 Mar)
 - [ ] Make new list to prepare for next campfire (w/b 21 Mar)
 
 Comments welcome! cc @elinw.

**Comment by hturner** [comment]
Ideas for translations session 1 (April)

Reference: https://contributor.r-project.org/translating-r-to-your-language/ video recording and slides.

 - Which languages are covered?
 - Can we analyse coverage? Based on the SVN mirror?
 - Some overview of process
 - What tools are required? open source software, e.g. if don't have required keypad
 - After some small tasks, start a big task that is carried on in second session to enable people to get their questions answered
 - Invite people that register to join R-Devel Slack if not already on it
 - Should advertise #core-translation channel as part of campfire promotion

**Comment by hturner** [comment]
Things to do in preparation for Collaboration Campfires on May 24 (translations session 2)
- [ ] Post a message on Slack with materials from Session 2 (# getting-started) and 3 (#getting-started) (Saranjeet, by May 5)
- [ ] Make blog post draft self-contained (how to contribute) (Saranjeet, by May 5)
- [ ] Post on #core-translations about adding contributions to the blog post and share on email with registered participants.  Invite Session 3 participants to Session 4 (not a problem if didn't attend session 3 - can still come!). Use Google Docs suggest feature to add further comments. Deadline for contributions: next campfire (May 24). (Saranjeet, by May 5)
- [ ] Email people from useR! translations tutorial to find out if anyone has worked on translations since? E.g. Indonesian. How best to add people to the team? (Heather, by May 3)
- [ ] Contact leaders of translation teams (Heather, by May 5)
    - Are they still active? Does team contact need to be updated?
    - Can they come, or can their teammates comes?
    - Explain more about the campfires and check best way for people to contribute?
    - Add a column: what version of R first included translations in their language?
- [ ] Confirm May 5 meeting with Appsilon. Discuss Session 4 and Bug BBQ. (Heather, Apr 28)
- [ ] Rewatch translation tutorial https://contributor.r-project.org/translating-r-to-your-language/ (Saranjeet, May 5)
- [ ] Find alternative to https://r-devel.slack.com/customize/get-started (Heather)
    - [ ] DM when people join Slack, maybe link to page on R Contributor website? 
    - [ ] Add description of all channels in #1_guide_to_this_slack. Reduce channels that people automatically join,: #0_welcome, #1_guide_to_this_slack, #get-started, #work-out-loud, #job-opportunities, #events, #random. Think about channel order.
    - [ ] Consider new channels #gsod, #gsoc
- [ ] Promotion on Twitter/Slack/LinkedIn
    - Note about people that only know English - can still help, think about alternative exercises.
- [ ] Email reminder to participants registered for Session 3 or 4
 - [ ] Check what tools are required. Open source software, e.g. if don't have required keypad for a particular language.
 - [ ] Follow-up promotion for Session 3 on Twitter and R-Devel Slack ?
 - [ ] Prep for Session 4 (practice) in more detail, i.e. skeleton for collaborative notes, test out activities
    * Poll 1: Did you come to sessions 3?
    * Logistics (Zoom, code of conduct, etherpad, etc). 
    * Poll 2: Did you watch the translation tutorial?
    * Activities: ideas from translations tutorial (longer activity where we translate into 2 or 3 languages).
        * Two simple examples: one from English to British English, one to Hindi
        * Discussion on social process with translation team leaders - how to join team, how to find translations that need updating, how to contribute. 
        * Use languages mentioned in Session 3
        * Invite experts on translation in R and/or the languages of interest
        * Guide through step by step of adding a translation, with cheat sheet to make it easier (e.g. translation already worked out)
    * Take home activity:?
    * Ask for specific help on #core-translation channel. 
    * Use #work-out-loud to work through particular example.
    * Advertise Bug BBQ.
    * Joining translation team/how to co-organize.
 - [ ] Attendance certificates for all session (Saranjeet)
 - [ ] Remove any confidential info from collaborative notes and share on the collaboration campfires webpage/GitHub.

**Comment by hturner** [comment]
Closing this now the planned series of Collaboration Campfires has completed. We can start a new issue for future Collaboration Campfires or other outreach.
